spring.application.name=travel-guide-app

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/travel_guide_app
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false

# ===============================
# SERVER
# ===============================
server.address=0.0.0.0
server.port=8080

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# JWT
# ===============================
jwt.secret=8aae2671166f0ee026d940c2ea843c23
jwt.expiration=86400000