ALTER TABLE trips 
ADD COLUMN IF NOT EXISTS number_of_days INT NOT NULL DEFAULT 1;

ALTER TABLE trips 
ADD COLUMN IF NOT EXISTS people_count INT;

ALTER TABLE trips 
ADD COLUMN IF NOT EXISTS representative_name VARCHAR(255);